/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.algebra;

import hr.algebra.model.Movie;
import hr.algebra.model.MovieTableModel;
import hr.algebra.parsers.rss.MovieParser;
import hr.algebra.utils.MessageUtils;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;
import javax.xml.stream.XMLStreamException;

/**
 *
 * @author Tin
 */
public class GetMovieFeedPanel extends javax.swing.JPanel {

    /**
     * Creates new form GetMovieFeedPanel
     */
    
    private List<Movie> downloadedMovies;
    private MovieTableModel movieTableModel;
    
    public GetMovieFeedPanel() {
        initComponents();
        initOther();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spMovies = new javax.swing.JScrollPane();
        tblMovies = new javax.swing.JTable();
        btnDownloadRss = new javax.swing.JButton();
        btnUploadDB = new javax.swing.JButton();

        tblMovies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spMovies.setViewportView(tblMovies);

        btnDownloadRss.setText("Download RSS");
        btnDownloadRss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadRssActionPerformed(evt);
            }
        });

        btnUploadDB.setText("Upload to Database");
        btnUploadDB.setEnabled(false);
        btnUploadDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadDBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnDownloadRss, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUploadDB, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spMovies, javax.swing.GroupLayout.PREFERRED_SIZE, 1180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spMovies, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDownloadRss, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUploadDB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDownloadRssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadRssActionPerformed
        // 1. parse
        // 2. put in DB
        // 3. load model
        try{
            downloadedMovies = MovieParser.parse();
            movieTableModel.setMovies(downloadedMovies);
            btnUploadDB.setEnabled(true);
        } catch (IOException | XMLStreamException ex) {
            Logger.getLogger(GetMovieFeedPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDownloadRssActionPerformed

    private void btnUploadDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadDBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUploadDBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDownloadRss;
    private javax.swing.JButton btnUploadDB;
    private javax.swing.JScrollPane spMovies;
    private javax.swing.JTable tblMovies;
    // End of variables declaration//GEN-END:variables

    private void initOther() {
        try {
            //setupRepo();
            setupTable();
        } catch (Exception ex) {
            Logger.getLogger(GetMovieFeedPanel.class.getName()).log(Level.SEVERE, null, ex);
            MessageUtils.showErrorMessage("Fatal error", "Something went horribly wrong ERROR:???");
            System.exit(1);
        }
    }

    private void setupRepo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setupTable() {
        tblMovies.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblMovies.setAutoCreateRowSorter(true);
        tblMovies.setRowHeight(25);
        movieTableModel = new MovieTableModel(new ArrayList<>());
        tblMovies.setModel(movieTableModel);
    }
}
